name: creativolabs
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.0.20
  go_router: ^14.6.2
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.0
  font_awesome_flutter: 10.8.0
  flutter_dotenv: ^5.2.1
  provider: ^6.1.2
  firebase_auth: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/images/
